import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import AppWrapper from "@/components/AppWrapper";
import ReduxProvider from "@/provider/ReduxProvider";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider
      appearance={{
        baseTheme: dark,
      }}
    >
      <html lang="en" className="">
        <body className={inter.className}>
          <ReduxProvider>
            {/* <Navbar /> */}
            <AppWrapper>{children}</AppWrapper>
          </ReduxProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
