import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Sound Vibe - Auth",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="h-screen w-full flex items-center justify-center">
          {children}
        </div>
      </body>
    </html>
  );
}
